### ISSUE TITLE
Deprecation warnings on ReactNative >=25.

### ISSUE THREAD

**Issue by andrey-skl** [Andr3wHur5t/react-native-keyboard-spacer#21]
https://github.com/facebook/react-native/releases/tag/v0.25.1

> Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Also this will stop working in 0.26. So we had to rewrite imports to avoid warnings.

**Comment by rturk** [comment]
Starting in RN 25 React Native import wil change. Requiring React API from react-native will be deprecated: https://github.com/facebook/react-native/releases/tag/v0.25.1

Instead of:

`import React, { Component, View } from 'react-native';
`

you should now:

```
import React, { Component } from 'react';
import { View } from 'react-native';
```

**You can also try this codemod built by the community to automatically rewrite all the imports.**
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by rturk** [comment]
@Andr3wHur5t There is a PR for this (https://github.com/Andr3wHur5t/react-native-keyboard-spacer/pull/19) can you merge it and publish a new major version?

**Comment by andrey-skl** [comment]
So, PR #19 is merged. Can this issue be closed?

**Comment by rturk** [comment]
Are you publishing a new version to NPM?

**Comment by Andr3wHur5t** [comment]
Just published a new major version to npm.
